public with sharing class ContactTriggerHandlerv2 {
    public static void afterInsertHandler(List<Contact> newContacts){
        Set<Id> accountIds = new Set<Id>();
        for(Contact con : newContacts){
            if(String.isNotBlank(con.AccountId)){
                accountIds.add(con.AccountId);
            }
        }
        AccountContactServicev2.updateActiveContacts(accountIds);
    }
    
    public static void afterUpdateHandler(List<Contact> newContacts, Map<Id,Contact> oldContactsMap){
        Set<Id> accountIds = new Set<Id>();
        for(Contact con : newContacts){
            if(String.isNotBlank(con.AccountId) && oldContactsMap.get(con.Id).Active__c != con.Active__c){
                accountIds.add(con.AccountId);
            }else if(oldContactsMap.get(con.Id).AccountId != con.AccountId){
                accountIds.add(con.AccountId);
                accountIds.add(oldContactsMap.get(con.Id).AccountId);
            }
        }
        AccountContactServicev2.updateActiveContacts(accountIds);
    }

    public static void afterDeleteHandler(List<Contact> oldContacts){
        Set<Id> accountIds = new Set<Id>();
        for(Contact con : oldContacts){
            if(String.isNotBlank(con.AccountId)){
                accountIds.add(con.AccountId);
            }
        }
        AccountContactServicev2.updateActiveContacts(accountIds);
    }

    public static void afterUndeleteHandler(List<Contact> newContacts) {
        Set<Id> accountIds = new Set<Id>();
        for(Contact con : newContacts){
            if(String.isNotBlank(con.AccountId)){
                accountIds.add(con.AccountId);
            }
        }
        AccountContactServicev2.updateActiveContacts(accountIds);
    }
}